# Generated by Django 2.1.4 on 2019-01-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20181229_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldoApertura',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='saldoFinal',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
