# Generated by Django 2.1.4 on 2019-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20190109_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancavirtual',
            name='dniTitularCuentaDestino',
            field=models.CharField(max_length=10),
        ),
    ]
