# Generated by Django 2.1.4 on 2019-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_auto_20190113_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('soltero', 'Solter@'), ('casado', 'Casad@'), ('viudo', 'Viud@'), ('divorciado', 'Divorciad@'), ('unionLibre', 'Unión Libre'), (None, 'Eliga una Opcion')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino'), (None, 'Eliga una Opcion')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro'), ('basica', 'Básica'), ('nomina', 'Nómina'), ('valores', 'Valores'), ('juvenil', 'Juvenil'), ('programado', 'Ahorro Programado'), ('euros', 'Ahorro en Euros'), (None, 'Eliga una Opcion')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia'), (None, 'Eliga una Opcion')], max_length=30),
        ),
    ]
